add solution for 7-module 2-task
js-tasks-ru/htmlcss-20210513_aleksandra41 pull request #19
Opened 2021-06-06 20:23 UTC by alex-nb

2021-06-06 20:24 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-08 14:20 UTC, GSemikozov requested changes

2021-06-08 14:20 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +    display: flex;
в другом ПР писал почему лучше inline-flex)

2021-06-08 15:28 UTC, alex-nb commented on 07-lection5/02-radio/radio.css
> +    display: flex;
Исправила на inline-flex, но это не решило проблему
Навесила на label width: min-content; в таком случае он не растягивается на всю ширину

2021-06-08 17:41 UTC, GSemikozov approved these changes

2021-06-08 17:41 UTC, merged