Main page
js-tasks-ru/htmlcss-20210513_aleksandra41 pull request #7
Opened 2021-05-24 21:26 UTC by alex-nb

2021-05-24 21:27 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-05-26 11:07 UTC, GSemikozov requested changes

2021-05-26 11:07 UTC, GSemikozov commented on components/header/header.css
> +.header__nav-item:first-child {
лучше использовать класс-модификатор (.header__nav-item_active) - скорее всего будет навешиваться js-ом и делать ссылку "выбранной/нажатой/активной")

2021-05-26 12:11 UTC, alex-nb commented on components/header/header.css
> +.header__nav-item:first-child {
Поправила

2021-05-26 12:11 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-05-26 12:14 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-05-26 12:16 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-05-26 13:52 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-05-26 21:36 UTC, GSemikozov approved these changes

2021-05-26 21:36 UTC, merged